name: vanguardmoney
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_ai: ^2.3.0
  provider: ^6.1.5+1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1
  image_picker: ^1.0.4
  intl: ^0.20.2
  google_mlkit_text_recognition: ^0.15.0
  record: ^6.1.2
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  # moved flutter_launcher_icons to dev_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

# Configuration for flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
